### ISSUE TITLE
iqoo表示阵亡

### ISSUE THREAD

**Issue by Liberations** [Joenothing-lst/Autojs-JNBJT#1]
能点击但是好像点不到特殊人

**Comment by Joenothing-lst** [comment]
1.日志有输出什么报错吗
2.点击准确吗
3.其实这个东西我还没在别的手机上测试过（

**Comment by Joenothing-lst** [comment]
现在会默认开启简单坐标模式了，如果使用方法2应该没问题（

**Comment by Liberations** [comment]
function work(flag) {
    sleep(SLEEP);
    click(SIZE[0] / 2, 650);
    sleep(SLEEP);
    if (flag) {
        var p = findImage(images.captureScreen(), this.sptemp, {
            region: [313, 573, 514, 809],
            threshold: 0.7
        });
        if (p) {
		    toast("找到理财");
            click(SIZE[0] / 2, 950);
            sleep(SLEEP);
        } else {
			toast("理财未找到");
            flag = false;
        }
    }
    reBack();
    reBack();
}

走到了理财未找到

**Comment by Liberations** [comment]
ok我试试方法2。

**Comment by Joenothing-lst** [comment]
region 参数是在指定区域内搜索模版，如果不在乎性能的话可以注释掉，意为全屏搜索模版

**Comment by Liberations** [comment]
方法二的局限性有点大我刚刚用华为p30搞 他的分辨率是1080x2340。方法二缩放不好控制，而且上下也不好对准。不然试试横屏最大化？竖屏地图最大化又看不到所有水井。很惆怅。晚上我也改改你的脚本。程序猿飘过。。。

**Comment by Liberations** [comment]
function clickJing(i, j) {
    click(540 + i * 55, 1045 + j * 55)
} 应该是这个方法得自己调整下才能正常

**Comment by Liberations** [comment]
我的想法是按宽度比列适配而不是写死像素点或计算出固定的像素点。对齐方式可以让地图最小化或者最大化再对齐。

**Comment by Joenothing-lst** [comment]
我自己一直用的都是竖屏，不过横屏版的也有，横屏版操作的确更简单，下班有空传一下。
至于宽度比例适配，游戏的ui好像是不受手机分辨率长宽比例影响的。

**Comment by Liberations** [comment]
忙活了一早上发现autojs的识图能力是真滴差。。。改天换其他的试试
